[workspace]
resolver = "3"
members = ["zenrc-log", "zenrc-bt", "zenrc-shm"]

[workspace.dependencies]
time = "0.3"
thiserror = "2"
crossbeam-channel = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
