[package]
name = "zenrc"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
zenrc-dds = { path = "../zenrc-dds" }
thiserror = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "dds_bench"
harness = false
