[package]
name = "zenrc-shm"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Shared memory for high-performance zero-copy communication"

[dependencies]
nix = { workspace = true, features = ["mman", "fs"] }
ctrlc = { workspace = true }
arrow = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }