[package]
name = "zenrc-shm"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { workspace = true, features = ["mman", "fs"] }
arrow = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }